### ISSUE TITLE
Open tabs programmaticaly does not work

### ISSUE THREAD

**Issue by coorasse** [flatlogic/bootstrap-tabcollapse#10]
Calling 
`activeTab.tab('show')` does not work on accordions. Still works on tabs.

**Comment by gaykov** [comment]
@coorasse thank you for submiting! In accordions you should use `activeTab.collapse('show')` instead of `tab('show')`. Example:
````
$('#collapseOne').collapse('show');
$('#collapseOne').collapse('hide');
````
