### ISSUE TITLE
Tab content should be moved, not replicated.

### ISSUE THREAD

**Issue by constantm** [flatlogic/bootstrap-tabcollapse#17]
Tab content should ideally be moved dynamically instead of just being replicated. Replicating it is fine if the content of the tab doesn't include any elements with IDs or forms which JS interacts with.

**Comment by julianxhokaxhiu** [comment]
@constantm I think you're using an old version or a buggy one of jQuery. Mine is moving perfectly and it's not keeping any "old" shadow of it in the DOM. If so, it's a jQuery bug (and browser compatibility related), not of this plugin itself.

**Comment by constantm** [comment]
That's awesome to hear. I've not really looked at this again since September of last year, but will probably need to do so sooner rather than later. :)
