### ISSUE TITLE
Scrolling issues on tab in mobile view

### ISSUE THREAD

**Issue by sunilraj036** [flatlogic/bootstrap-tabcollapse#20]
In my case I have two tabs with large data, on clicking of second tab the page scroll goes to bottom og the page. How can i retain on the tab title. Any help will be appreciated.

Thanks,
Sunilraj Chavan

**Comment by smartapant** [comment]
@sunilraj036, in bootstrap-tabcollapse we use standard bootsrap collapse, so to do what you want to do you should read bootstrap's docs and write some custom code. Hope this stackoverflow question will be helpful http://stackoverflow.com/questions/20633087/how-can-i-make-bootstrap-3-collapsed-accordion-panels-load-at-top-of-their-conte
