### ISSUE TITLE
Dynamic Tab Labels (Values) Doesn't Load In Accordion Views

### ISSUE THREAD

**Issue by natarajanp** [flatlogic/bootstrap-tabcollapse#21]
Hi Team,

I've been using the tabCollapse for the last few days and it is awesome. But there is a small issue.

I'm passing dynamic values to the tab header and it works well in tab view (Desktop View). But in the mobile view (Loading page in mobile ) AngularJS is not rendering the dynamic value in the header. Is this a known issue?. Could you team please help me in getting the same resolved.

Kind Regards,
Natarajan

**Comment by smartapant** [comment]
Thank you, @natarajanp. Our team will think on this issue. You will be notified if the solution appears.

**Comment by smartapant** [comment]
@natarajanp, the bug is fixed starting from 0.2.6 version.
