### ISSUE TITLE
Collapsed tab should have heading clickable

### ISSUE THREAD

**Issue by pmaselkowski** [flatlogic/bootstrap-tabcollapse#24]
To activate standard tab user can click anywhere and it will activate.

Collapsed tabs have only label clickable. 

In my optinion entire `.panel-heading` should be clickable.

**Comment by okendoken** [comment]
Hi @pmaselkowski.

Thanks for report.

Please take a look at bootstrap panel implementation http://getbootstrap.com/javascript/#collapse
It's only link clickable there

**Comment by okendoken** [comment]
btw, it was already discussed in #2. Please check it

**Comment by pmaselkowski** [comment]
Well, my first impression after cheking demos was that it was missing something from collapsed mode, good that there is workarond for it, thanks.

**Comment by okendoken** [comment]
no problem :)
closing
