### ISSUE TITLE
Missing .panel-active class

### ISSUE THREAD

**Issue by julianxhokaxhiu** [flatlogic/bootstrap-tabcollapse#25]
I was using your awesome snippet to accomplish the same goal and the only that I've found missing in your code is that active panels are missing the native bootstrap class `panel-active` where `panel panel-default` are.

Can you please fix this? Thanks in advice :)

**Comment by julianxhokaxhiu** [comment]
Nvm, I found a way to do this using events :) Thanks anyway!

**Comment by okendoken** [comment]
@julianxhokaxhiu no problem :)
