### ISSUE TITLE
Error with data-target and href

### ISSUE THREAD

**Issue by babwar** [flatlogic/bootstrap-tabcollapse#31]
Hello,

With tab, wee can keep href to a specific url (for seo) and toogle tabs with data-target.
ex : &lt;li&gt;&lt;a href=&quot;http://my-url.com&quot; data-target='#profile' data-toggle=&quot;tab&quot;&gt;Profile&lt;/a&gt;&lt;/li&gt;

with plugin it becomes :
&lt;h4 class=&quot;panel-title&quot;&gt;
    &lt;a ... data-target=&quot;#profile&quot; href=&quot;#profile-collapse&quot; ...&gt;Profile&lt;/a&gt;
&lt;/h4&gt;

As you see : data-target="#infos" href="#infos-collapse" make collapse not working properly

**Comment by ali-khan-confiz** [comment]
you have to edit in library by replacing href with data-target (not on all places) it will work then i have done that too
