### ISSUE TITLE
Open page with accordion closed

### ISSUE THREAD

**Issue by stassinari** [flatlogic/bootstrap-tabcollapse#32]
Hello,

at work it's been requested that, on mobile, accordions should appear closed on page load.

I haven't found an option to do this, so I modified the source in a couple of lines:
@line35: removed the ternary operator

``` javascript
<div id="' + groupId + '" class="panel-collapse collapse ">'
```

@line124: removed the ternary operator

``` javascript
$heading.addClass('js-tabcollapse-panel-heading collapsed');
```

Since I just need closed accordion on the project, this solution _works_, but it's far from perfect.

It would be great to add a flag as an option, but I'm not very good with js and I don't know if I will find the time.

Just thought it might be useful for somebody with the same issue.

**Comment by CoralSilver** [comment]
+1 for this to be a configurable option.
