### ISSUE TITLE
Open tab according to weekday

### ISSUE THREAD

**Issue by shirokoweb** [flatlogic/bootstrap-tabcollapse#37]
Hi,
I'm using jquery UI to date. My tabs are open depending on weekday and I'm replacing the text with 'aujour'dhui' (today) :
$('#tabs').tabs();
$("#tabs").tabs("option", "active", ((new Date().getDay() || 7) - 1));
$('#tabs .ui-state-active a').text('Aujourd\'hui');
I'd like to know how I would add my piece of code to get it work with your contribution.
Thanks in advance for your reply.

**Comment by gaykov** [comment]
Hello!

You can call function `tab('show') ;` to show tab and `text()` to set value. Simple code:
```javascript
// Your tab should has some selector. tab-1 for Monday, for example
$('.nav-tabs .' + ((new Date().getDay() || 7) - 1)).tab('show');
$('.tab-pane.active').text('Aujourd\'hui');
```
