### ISSUE TITLE
Hash tag

### ISSUE THREAD

**Issue by Vega15** [flatlogic/bootstrap-tabcollapse#39]
Is there a way to get both tab and panel view:
a) load tab/panel based on a hash tag in url (example.html#tab3) and
b) update hash tag in window url based on tab/panel navigated to?

Thank you for your time

**Comment by gaykov** [comment]
Hello!

Try to add this js-code to the page:
```javascript
var url = document.location.toString();
if (url.match('#')) {
    $('.nav-tabs a[href=#'+url.split('#')[1]+']').tab('show') ;
}

$('.nav-tabs a').on('shown.bs.tab', function (e) {
    window.location.hash = e.target.hash;
});
```

**Comment by Vega15** [comment]
Thank you for your help and quick response. On load part works perfect. The navigational part works great on tabs, but stops working in the panel view. Is there a different parameter needed?

**Comment by gaykov** [comment]
I think you need to choose correct jQuery selectors.

**Comment by Vega15** [comment]
Added this for panels:
$(document).on("shown.bs.collapse", ".panel-collapse, a[data-toggle='tab']", function (e) {
	window.location.hash = this.id;
});

So final version is like following:
var url = document.location.toString();
if (url.match('#')) {
    $('.nav-tabs a[href=#'+url.split('#')[1]+']').tab('show') ;
}
$('.nav-tabs a').on('shown.bs.tab', function (e) {
	if(history.pushState) history.pushState(null, null, '#'+$(e.target).attr('href').substr(1)); 
	else location.hash = '#'+$(e.target).attr('href').substr(1);
});
$(document).on("shown.bs.collapse", ".panel-collapse, a[data-toggle='tab']", function (e) {
	window.location.hash = this.id;
});

Spasibo za pomosh'
