### ISSUE TITLE
Feature: option to use "collapse" or "accordion"

### ISSUE THREAD

**Issue by mattez** [flatlogic/bootstrap-tabcollapse#45]
Accordion is cool but I need only basic "collapse" functionality. => Panels keep opened, not auto collapsed, more panels can be opened at the same time.

Difference is only in specifying "data-parent" attribute. If it is specified it behaves as accordion, if not is simple collapse.
In actual version, it is on line 106:

``` javascript
'data-parent': '#' + parentId,
```

It would be nice to specify this in options. Something like

``` javascript
$( "#nav-tabs--fleet" ).tabCollapse( {
    accordion: true
} );
```

``` javascript
if(this.options.accordion){
    'data-parent': '#' + parentId,
}
```

It would be helpful.
Or there is some another workaround?

**Comment by mattez** [comment]
Generally: this library is called "tabcollapse" not "tabaccordion". So in first place, it should behave like simple collapse and accordion should extend the default collapse behavior.

**Comment by mattez** [comment]
I created a pull request with basic implementation of this feature.

**Comment by geoffrey-eisenbarth** [comment]
This is what I needed too, thanks for doing the legwork. Wish the pull would be accepted :(
