### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by designnik** [flatlogic/bootstrap-tabcollapse#48]
I am using bootstrap-tabcollapse on modal box. On desktop view work well, but, on small (device) view does not work hidden-xs and visible-xs. when we rotate screen it will be fine.

**Comment by repoYoda** [comment]
I have the exactly same issue.
The description is:
* when the page is loaded in mobile width (the collapse component should be displayed), the collapse component won't be displayed until the window is resized.
* once the resize has been made, the content appears.
* when closing the modal and opening it again the content is there (does not need the resize)
* on page refresh the issue occurs again

**Comment by repoYoda** [comment]
Fixed the problem.
you need to call out tabcollapse on modal show event like this:

$('#IdOfYourModal').on('shown.bs.modal', function () {
	$('#MyTabs').tabCollapse();
});

**Comment by designnik** [comment]
Thanks Mate, Great! Job.

**Comment by Chethannp** [comment]
Hi, I am having the same problem! I am using your code to place it inside bootstrap Dropdown, It works fine on desktop but on mobile the content inside the Dropdown is blank where as on browser resize it works well.. Requesting you to please help me!! Thanks in advance.

**Comment by ali-khan-confiz** [comment]
use $(window).resize(); in you code at start of you application it will work

**Comment by amirhsh** [comment]
@ali-khan-confiz  Where should it be placed? how?

**Comment by ali-khan-confiz** [comment]
@amirhsh may be at the end of document.ready function if you are working with simple JS without any framework or at the place which would render when DOM would be loaded totaly

**Comment by amirhsh** [comment]
@ali-khan-confiz Thank you so much.
Here was my problem:
The page containing tab bar is hide I used it when that page is show. Then I call $(window).resize();
