### ISSUE TITLE
Tabcollapse did not appear in small screen

### ISSUE THREAD

**Issue by nev3rmi** [flatlogic/bootstrap-tabcollapse#52]
In the big screen it seems to work well, however in the small screen it doesn't show anything, but when I resize it appears ? Can anyone help me, Thanks !

Here is my code: Pls use http://www.freeformatter.com/html-formatter.html to make it easy to look @@ i cannot format it

<textarea rows="50">

<div class="boxmargin">
<ul id="orderTab" class="nav nav-pills nav-justified" style="margin-bottom: 15px;">
                  <li class="hvr-sweep-to-right active"><a class="textintab" href="#step2" data-toggle="tab">Step 2: Verify Information</a></li>
                  <li class="hvr-sweep-to-right"><a class="textintab" href="#step3" data-toggle="tab">Step 3: Review the CART</a></li>
                  <li class="hvr-sweep-to-right"><a class="textintab" href="#step4" data-toggle="tab">Step 4: Chossing Payment Method</a></li>
                </ul>
                <div id="orderTabContent" class="tab-content" >
                  <div class="tab-pane fade in active" id="step2">
                    <div id="hidethisinfo">
                      <h1>Step 2: Verify Information</h1>
                      <div class="form-group">
                        <label for="usr">Name:</label>
                        <input type="text" class="form-control" id="usr">
                      </div>
                      <div class="form-group">
                        <label for="ads">Address:</label>
                        <input type="text" class="form-control" id="ads">
                      </div>
                      <div class="form-group">
                        <label for="con">Contact Number:</label>
                        <input type="text" class="form-control" id="con">
                      </div>
                      <div class="form-group">
                        <div class="row">
                          <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                            <label for="hoo">Home:</label>
                            <input type="radio" class="form-control" id="hoo" value="1" name="hoo">
                          </div>
                          <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                            <label for="hoo">Office:</label>
                            <input type="radio" class="form-control" id="hoo" value="2" name="hoo">
                          </div>
                        </div>
                      </div>
                    </div>
                    <h1>Step 2b: Another Address to Delivery ?</h1>
                    <div class="form-group">
                      <label for="spd">Click here</label>
                      <input type="checkbox" class="form-control" id="spd">
                    </div>
                    <div class="form-group" id="otherinfo1">
                      <label for="name2">Name:</label>
                      <input type="text" class="form-control" id="name2">
                    </div>
                    <div class="form-group" id="otherinfo1">
                      <label for="ads2">Address:</label>
                      <input type="text" class="form-control" id="ads2">
                    </div>
                    <div class="form-group" id="otherinfo2">
                      <label for="pho2">Contact Number:</label>
                      <input type="text" class="form-control" id="pho2">
                    </div>
                  </div>
                  <div class="tab-pane fade" id="step3">
                    <h1>Step 3: Review the CART</h1>
                    <div id="receiveorder"></div>
                  </div>
                  <div class="tab-pane fade" id="step4">
                    <h1>Step 4: Chossing Payment Method</h1>
                  </div>
                </div>
</div>

<script type="text/javascript" src="<?php echo $url?>js/bootstrap-tabcollapse.js"></script> 

  <script>
    $('#orderTab').on('shown-accordion.bs.tabcollapse', function (e) {
    console.log('accordion about to be shown');
    });
    $('#orderTab').tabCollapse();
    </script> 
</textarea>

**Comment by ali-khan-confiz** [comment]
sorry i cant understand you html right now but i have same problem in my code too please add 
$(window).resize();

**Comment by borisNG** [comment]
@ali-khan-confiz  thanks since two days i've been working on it

**Comment by sandeep-barla** [comment]
**$(window).resize();** where can I add this

**Comment by sandeep-barla** [comment]
@borisNG **$(window).resize();** where can I add this

**Comment by borisNG** [comment]
@sandeep-barla  its been a long time but i think to do that you should add it on right after the window load event
