### ISSUE TITLE
Extending for Bootstrap 4

### ISSUE THREAD

**Issue by ghost** [flatlogic/bootstrap-tabcollapse#58]
First of all: Thanks for this really helpful plugin. As this functionality also isn´t part of Bootstrap 4 (although it´s really necessary for full responsive sites) here is the (short and easy) way to use this plugin with bootstrap 4:

Simply change the used CSS Classes for showing/hiding the elements to "hidden-lg-up" and "hidden-md-down":

```
TabCollapse.DEFAULTS = {
    accordionClass: 'hidden-lg-up',
    tabsClass: 'hidden-md-down',
    accordionTemplate: function(heading, groupId, parentId, active) {
        return  '<div class="panel panel-default">' +
                '   <div class="panel-heading">' +
                '      <h4 class="panel-title">' +
                '      </h4>' +
                '   </div>' +
                '   <div id="' + groupId + '" class="panel-collapse collapse ' + (active ? 'in' : '') + '">' +
                '       <div class="panel-body js-tabcollapse-panel-body">' +
                '       </div>' +
                '   </div>' +
                '</div>'

    }
};
```

**Comment by justcfx2u** [comment]
I made a slightly more comprehensive update to use v4 cards instead of panels.
At the time of this writing it has not gone through extensive testing but it seems to work well for now.

For those interested, it is available [here](/justcfx2u/bootstrap-tabcollapse/tree/twbs-v4).
