### ISSUE TITLE
Issue on browser resize

### ISSUE THREAD

**Issue by khaldoundanaf** [flatlogic/bootstrap-tabcollapse#60]
I have been testing different views of the plugin.. Having 3 tabs, when I open the browser in large viewport (tabs view) and select tab 1, then resize the browser to the small viewport (accordion view) and select tab 2, then resize the browser back to the original viewport, tab 2 will still be selected in the tab headers but the content will be the content of tab 1.

**Comment by blazmanx** [comment]
I don't know if it's the best solution, but to solve this probem I have modified the TabCollapse.prototype._initAccordion function by adding the following code a the end of the function :

```javascript
$(document).on("show.bs.collapse hide.bs.collapse", "#" + accordionId + " div[id$='-collapse']", function (e) {
	var sTabPaneId = $(this).attr('id').replace(/-collapse$/g, '');
	switch(e.type) {
		case "show" :
			$("#" + sTabPaneId).addClass('in active')
			break;
		case "hide" :
			$("#" + sTabPaneId).removeClass('in active')
			break;
	}
	
});
```
