### ISSUE TITLE
nothing is inserted to panel-group

### ISSUE THREAD

**Issue by shaniqwa** [flatlogic/bootstrap-tabcollapse#64]
Hi, 
I'm trying to use this cool plugin but when the original tabs are hidden, nothing else appears.. 
I noticed that the plugin is suppose to gather all tab-pane classes and insert them to the panel-group which should be visible when screen in small. any ideas what can fix this ? 
thanks
Shani

**Comment by GregOnNet** [comment]
Hi @shaniqwa,

I encountered the same issue and created a PR for it: https://github.com/flatlogic/bootstrap-tabcollapse/pull/68
Please vote. :smiley: 

//cc @DimaSavchenko
