### ISSUE TITLE
Make the entire tab clickable when collapsed 

### ISSUE THREAD

**Issue by andrey613** [flatlogic/bootstrap-tabcollapse#67]
I need to make the entire tab clickable when the tabs are in collapse mode

**Comment by GregOnNet** [comment]
Hey @andrey613,

I think that your issue can be solved without any changes on `bootstap-tabcollapse`.

You can simply update the concerned `a`-Tag having `display: block` set via CSS.

Hope this helps you out.

Kinds
Greg

**Comment by equiman** [comment]
@andrey613 hope it's help. Just with CSS

```
/* Tab Collapse */
a.js-tabcollapse-panel-heading {
  display: block;
  text-align: center;
}
```

**Comment by nucklehead** [comment]
This pull request should fix this. #72
