### ISSUE TITLE
Script impact multiple tabs on a page

### ISSUE THREAD

**Issue by cedricweatherly** [flatlogic/bootstrap-tabcollapse#74]
Ran into an issue when using multiple tabs on a page. The script seems to affect any/all Tabs on the page regardless of what is being targeted. 

for example I have 2 tabs, **#mainTab** and **#secondTab**; #mainTab is the only tab being targeted for changing to an accordion...like so: 

`$('#mainTab').tabCollapse();`

however, the script seems to impact both Tabs on the page -  secondTab is changing to an accordion. Is there any way to prevent this from happening...is there already a way to limit what the script is affecting? Should there be a Parent Class option added to the script with conditions to only target what's within that  Parent Class to prevent accordion behavior to other tabs on page. I can see a case for all tabs on the page needing to go from tab to accordion...but I also need an option to prevent this from applying to all tabs on a page.

**Comment by Ben-TangentDesign** [comment]
If you look at the code there is a setting to choose which div tab-content you want to select. So for example:

`$('#myTab2').tabCollapse({
		tabContentSelector: '.myTab2'
 });`

Then in your html markup:

`<ul id="#myTab2 class="nav nav-tabs" style="margin-bottom: 15px;">
       <li>MENU HERE</li>
</ul>`
 `<div id="myTabCo" class="tab-content myTab2" > 
            <div class="tab-pane fade">
		...
            </div>
</div>`
