### ISSUE TITLE
How to trigger/active tab buy internal anchor link

### ISSUE THREAD

**Issue by vivek-yes** [flatlogic/bootstrap-tabcollapse#82]
For example: I have two pages one with some html links and the other page has tabcollapse component. If I click a link in first page it should open the other page with respective tabs to be highlighted. Is it possible?

**Comment by yr4ik** [comment]
```
$('.show-tab').on('click', function(){
	var 
		target = $(this).data('target')||$(this).attr('href'),
		data = $('#myTab').data('bs.tabcollapse');
		
	if(!data._accordionVisible)
		data.$tabs.find('a[href="'+target+'"]').click();
	else
		data.$accordion.find('.panel-heading a[href="'+target+'-collapse"]').click();
	
	return false;
})
```
html:
`<a href="#my-tab-id" class="show-tab">open tab id my-tab-id</a>`
